In [2]:
import tensorflow as tf

print('즉시 실행 모드: ', tf.executing_eagerly())

# Tensor 생성
print(1, type(1))
print(tf.constant(1), type(tf.constant(1)))     # 0D Tensor - scala
print(tf.constant([1]), type(tf.constant([1])))     # 1D Tensor - 1차원 배열이라 생각
print(tf.constant([[1]]), type(tf.constant([[1]])))     # 2D Tensor - 2차원 배열이라 생각

print()
a = tf.constant([1, 2])
b = tf.constant([3, 4])
c = a + b
print(c)
d = tf.constant([3])
e = c + d
print(e)
f = tf.add(c, d)
print(f)


즉시 실행 모드:  True
1 <class 'int'>
tf.Tensor(1, shape=(), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor([1], shape=(1,), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor([[1]], shape=(1, 1), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>

tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor([7 9], shape=(2,), dtype=int32)
tf.Tensor([7 9], shape=(2,), dtype=int32)


In [8]:
print(7)
print(tf.convert_to_tensor(7, dtype=tf.float32))
print(tf.cast(7, dtype=tf.float32))
print(tf.constant(7.0))
print(tf.constant(7, dtype=tf.float32))

# numpy의 ndarray와  tensor 사이에  type이 자동 변환됨
import numpy as np
arr = np.array([1, 2])
print(arr, type(arr))

tfarr = tf.add(arr, 5)      # 5가 자동으로 tensor로 변환
print(tfarr)

tf.print(tfarr)
print(tfarr.numpy())
print(np.add(tfarr, 3))

7
tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(7.0, shape=(), dtype=float32)
[1 2] <class 'numpy.ndarray'>
tf.Tensor([6 7], shape=(2,), dtype=int64)
[6 7]
[6 7]
[ 9 10]


In [4]:
# 텐서플로는 텐서를 Graph 영역내에서 실행하는 것이 일반적이다.
g1 = tf.Graph() # 별도의 그래프 생성
with g1.as_default():
    c1 = tf.constant(1, name='c_one')
    print(c1)
    print(type(c1))
    print(c1.op.node_def)

Tensor("c_one:0", shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.SymbolicTensor'>
name: "c_one"
op: "Const"
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
      }
      int_val: 1
    }
  }
}
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}

