In [28]:
# tf에서 변수 선언 후 사용
import tensorflow as tf

f = tf.Variable(1.0)
v = tf.Variable(tf.ones((2,)))
m = tf.Variable(tf.ones((2,1)))
print(f)
print(v)
print(m)
tf.print(m)

print()
v1 = tf.Variable(1)
v1.assign(10)       # 변수에 값을 할당
print(v1)

v2 = tf.Variable(tf.ones(shape=(1)))
v2.assign([20])
print(v2)

v3 = tf.Variable(tf.ones(shape=(1,2)))
v3.assign([[30, 40]])
print(v3)


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>
[[1]
 [1]]

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>
<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([20.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[30., 40.]], dtype=float32)>


In [29]:
v1 = tf.Variable([3])
v2 = tf.Variable([5])
v3 = v1 * v2 + 10
print(v3)
print()
var = tf.Variable([1,2,3,4,5], dtype=tf.float32)
result = var + 10
print(result)

print()
w = tf.Variable(tf.ones(shape=(1,)))
b = tf.Variable(tf.ones(shape=(1,)))
w.assign([2])
b.assign([3])

def func1(x):
    return w * x + b

out_a1 = func1([3])
print('out_a1: ', out_a1)
print(type(func1))

print()
@tf.function
def func2(x):
    return w * x + b

out_a2 = func2([1, 2])
print('out_a2: ', out_a2)
print(type(func2))

tf.Tensor([25], shape=(1,), dtype=int32)

tf.Tensor([11. 12. 13. 14. 15.], shape=(5,), dtype=float32)

out_a1:  tf.Tensor([9.], shape=(1,), dtype=float32)
<class 'function'>

out_a2:  tf.Tensor([5. 7.], shape=(2,), dtype=float32)
<class 'tensorflow.python.eager.polymorphic_function.polymorphic_function.Function'>


In [ ]:
# 난수
rand = tf.random.uniform([4], 0, 1) # 균등 분포
print(rand)
rand2 = tf.random.normal([4], 0, 1) # 균등 분포
print(rand2)

aa = tf.ones((2, 1))
print(aa.numpy())
m = tf.Variable(tf.zeros((2, 1)))
print(m.numpy())
m.assign(aa)        # 치환
print(m.numpy())
m.assign_add(aa)    # 더하기 후 치환
print(m.numpy())
m.assign_sub(aa)    # 빼기 후 치환
print(m.numpy())

tf.Tensor([0.5432131  0.80746686 0.09020114 0.62945044], shape=(4,), dtype=float32)
tf.Tensor([ 0.32317182  1.2869878   0.9298429  -0.57262367], shape=(4,), dtype=float32)
[[1.]
 [1.]]
[[0.]
 [0.]]
[[1.]
 [1.]]
[[2.]
 [2.]]
[[1.]
 [1.]]
